spring:
  profiles:
    active: ${APP_PROFILE:dev}
  devtools:
    add-properties: false
  main:
    banner-mode: "CONSOLE"   # por algum motivo tem que ser entre aspas duplas
    allow-bean-definition-overriding: true  
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:MongoDB2025!@localhost:27017/customer-service?authSource=admin
      database: product-service
      auto-index-creation: true
      uuid-representation: standard

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: INFO
    br.matosit.customer_service: INFO
  pattern: 
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [X-ReqID=%X{X-ReqId}] [%-5level] [%logger{70}] - %msg%n"

cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

springdoc:
  api-docs:
    path: "/api-docs"

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 
      
