name: Feature Branch Validation

on:
  push:
    branches:
      - 'feature/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Unit Tests
        run: mvn test

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

  create-pull-request:
    runs-on: ubuntu-latest
    needs: [unit-tests, security-scan]
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name 'Luis Matos'
          git config --global user.email 'luismatos000@gmail.com'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: develop
          branch: ${{ github.ref }}
          title: 'Automated Pull Request from Feature Branch'
          body: 'This pull request was automatically created by GitHub Actions.'
          labels: 'automated'
          assignees: 'matosit'
          