
name: Simulate Production Deploy and Create Release PR

on:
  pull_request:
    types: [closed]
    branches:
      - release/**

jobs:
  simulate-deploy:
    name: Simulate Production Deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: mvn clean install

      - name: Simulate Deploy
        run: echo "Simulating deploy to production environment"

  create-release-pr:
    name: Create Release PR
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: simulate-deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name 'Luis Matos'
          git config --global user.email 'luismatos000@gmail.com'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: master
          branch: ${{ github.head_ref }}
          title: 'Release PR from Release Branch'
          body: 'This pull request was automatically created by GitHub Actions.'
          labels: 'release'
          assignees: 'matosit'

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: create-release-pr
    steps:
      - name: Await manual approval
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ needs.create-release-pr.outputs.pull-request-number }}
