name: Simulate Production Deploy and Create Release PR

on:
  pull_request:
    types: [closed]
    branches:
      - release/**

jobs:
  simulate-deploy:
    name: Simulate Production Deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Simulate Deploy
        run: echo "Simulating deploy to production environment"

  create-pull-request:
    name: Create Release PR
    runs-on: ubuntu-latest
    needs: simulate-deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name 'Luis Matos'
          git config --global user.email 'luismatos000@gmail.com'

      - name: Get latest release branch
        id: get-latest-release-branch
        run: |
          LATEST_RELEASE_BRANCH=$(git branch -r | grep 'release/' | sort -V | tail -n 1 | sed 's/origin\///')
          echo "latest_release_branch=${LATEST_RELEASE_BRANCH}" >> $GITHUB_ENV
          echo "Latest release branch: ${LATEST_RELEASE_BRANCH}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: master
          branch: ${{ env.latest_release_branch }}
          title: 'Release PR from Release Branch'
          body: 'This pull request was automatically created by GitHub Actions.'
          labels: 'release'
          assignees: 'matosit'
